// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdmakgndzntvfoldkgep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkbWFrZ25kem50dmZvbGRrZ2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzY2NTMsImV4cCI6MjA2NDk1MjY1M30.04MKQfJ_VaKYqAm7_CBnRLZYPyYjmZBzIEQzW48GT3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);